### ISSUE TITLE
Assert counting not working

### ISSUE THREAD

**Issue by khru** [TypedDevs/bashunit#117]
#### Summary
When running an assertion inside other assertion the assertion count it's not been incremented

#### Current behavior

If we have to assertions nested it only counts 1
![Assert count not working](https://github.com/TypedDevs/bashunit/assets/6353105/1da43123-dc74-449f-b44b-ed03cde5dd47)

#### How to reproduce

```bash
function test_xxx() {
  assertEmpty "$(assertEquals "hello world" "hello world")"
}
```
```
./bashunit ./tests/**/*.sh --filter xxx
```

This is only one assert but has two

```bash
function test_xxx1() {
 assertEquals "hello world" "hello world"
}
```

this only has one and has the same count of assertions

**Comment by cmayo** [comment]
In case we want to count the asserts within the subshell, all tests testing the negative case will count as failing assert. I mean:

```
function test_unsuccessful_assert_equals() {
  assert_equals\
    "$(Console::printFailedTest "Unsuccessful assert equals" "1" "but got" "2")"\
    "$(assert_equals "1" "2")"
}
```

In this case the `assert_equals "1" "2"` will count as failed assert

**Comment by Tito-Kati** [comment]
Do we want these assertions to count? I mean, a regular user should never need to assert an assertion, only we need to do it, since the library is testing itself. In our case, it's desirable for these assertions not to count, right?

Additionally, as @cmayo points out, if these assertions also counted, then our tests that check for failure return would be counted as failed.
