### ISSUE TITLE
Add skip and todo to the framework

### ISSUE THREAD

**Issue by khru** [TypedDevs/bashunit#21]
Add:
- `todo`
- `skip`

To our test frameworks to enable good practices like the todo tech. explained by Kent Beck in his book Test-Driven Development.

Examples:
- Jest: https://jestjs.io/docs/api#testskipname-fn
- PHPUnit: https://docs.phpunit.de/en/9.6/incomplete-and-skipped-tests.html#incomplete-tests

I consider that the syntax and naming from jest are better.

@Tito-Kati Pending review the colors to display this

**Comment by Chemaclass** [comment]
I think for this we could simply prefix a test with skip/todo to mark them as such. Eg:
- `skip_test_foo(){ ... }`
- `todo_test_bar() { ... }`

**Comment by Tito-Kati** [comment]
@Chemaclass It could be a way, but I want to highlight the following for everyone to consider: if we do it this way, perhaps these tests won't stand out enough in the code. Although prefixing them this way is the most "vanilla" approach, it also risks a test not being counted due to a typo. Indeed, an interesting point of this feature is to tally the tests marked as 'todo' or 'skipped'.

**Comment by Chemaclass** [comment]
> @Chemaclass It could be a way, but I want to highlight the following for everyone to consider: if we do it this way, perhaps these tests won't stand out enough in the code. Although prefixing them this way is the most "vanilla" approach, it also risks a test not being counted due to a typo. Indeed, an interesting point of this feature is to tally the tests marked as 'todo' or 'skipped'.

Similar as when looking for tests (any function that starts with `test*`), we could do the same for the prefix `skip[tT]est*` and `todo[tT]est*`, and then use the number of them to display it in the output.

**Comment by khru** [comment]
@Tito-Kati commented that these could be better:

https://docs.phpunit.de/en/9.6/incomplete-and-skipped-tests.html

**Comment by Tito-Kati** [comment]
To add context to what @khru says, I found it more accurate to skip/todo tests using a function rather than doing it by the test name.

This way, for instance, we can skip a test when certain conditions are met, such as not being able to launch a test on a specific operating system (as it happened to us, for example, with the execution time feature and macOS).

**Comment by Chemaclass** [comment]
In PHPUnit, this is the output for uncompleted and skipped tests:

<img width="838" alt="Screenshot 2023-09-10 at 18 11 37" src="https://github.com/Chemaclass/bashunit/assets/5256287/cad61016-0534-4873-8153-137ff1a3ae91">
