### ISSUE TITLE
Example on how to test a function

### ISSUE THREAD

**Issue by pmusset** [TypedDevs/bashunit#233]
In the examples [here](https://github.com/TypedDevs/bashunit/blob/main/example), I think it misses one that shows how to test a specific function in a script. 

For example, in a directory organised like that, as describe in your quickstart guide, 
```
.
├── lib
│   └── bashunit
├── example.sh
└── tests
    └── example_test.sh
 ```
 I am not sure what I have to write in `example_test.sh` to test a function in `example.sh`. Should I source `example.sh` ? But according to your own tests (for example  [here](https://github.com/TypedDevs/bashunit/blob/main/tests/unit/assert_test.sh))  it doesn't seem to be the case.

**Comment by antonio-gg-dev** [comment]
Hello @pmusset ! First of all, thank you very much for using bashunit!

You are correct, you should add `source example.sh` at the beginning of your example_test.sh, personally, I recommend you do it within the [set_up function](https://bashunit.typeddevs.com/test-files#set-up-function).
```
function set_up() {
  source example.sh
}
```

This way, all the functions within the file will be loaded from scratch before each test inside that file is executed.

In the example you mentioned, we are not using source because bashunit uses itself for testing, so it doesn't need to import its own functions as they have already been imported previously in the runtime.

**But the standard is to have to do it.**

I hope I have resolved your doubts and if you have any other questions do not hesitate to let us know.

**Comment by antonio-gg-dev** [comment]
I also wanted to thank you for giving us feedback on the example @pmusset . You are absolutely right. I will add it as soon as possible, but if you want, you can do it yourself and make us a PR, we would really appreciate it a lot.

**Comment by Chemaclass** [comment]
Thanks for your feedback, @pmusset. I created [this PR](https://github.com/TypedDevs/bashunit/pull/234) to split the example into two: one to test bash functions and another to test an executable bash script. Does this helps?

**Comment by Chemaclass** [comment]
@pmusset, that would depend on the way you are designing your logic. 
There is no right or wrong here, and for either way, you can have tests for it.

My personal preference: 
1) I prefer to have isolated functions and test them from an isolated perspective for small/unit tests. 
2) And then, also some more generic tests which need to be "sourcing" the whole file as that's how you execute a bash script in the end.

**Comment by Chemaclass** [comment]
Closed as the question was answered and the example code was improved here https://github.com/TypedDevs/bashunit/pull/234
