### ISSUE TITLE
When a failing test is found, display it again

### ISSUE THREAD

**Issue by Chemaclass** [TypedDevs/bashunit#294]
## Current

Right now, when there are hundred of tests and one of them is failing, you dont know the details immediately.
To find the failing test, you need to do scroll up until you find the failing test details.

## Expected 

Display the failing tests immediately right after finishing all tests execution.

**Comment by staabm** [comment]
I think this is one of the issues we were talking about at phpdd24.

here are a few ideas which might help fixing them. Since I am not a expert of this codebase here, please take this suggestions with a grain of salt :).

I think output of a test when beeing run should be redirected into a tempfile, or a variable - so it doesn't show up immediately in the terminal. that way you can decide what todo with that output.
e.g. append all the output of failling tests in this variable/file and output it at the very end (so succeeded test output would not be intermixed).
alternatively maybe its already enough to output the buffered content from said tempfile/variable, in case the test was identified as beeing failed.
