### ISSUE TITLE
Make asserting failed exit codes and output nicer

### ISSUE THREAD

**Issue by ondrejmirtes** [TypedDevs/bashunit#334]
Creating this based on our discussion in Dresden :)

If we want to assert that a command failed & assert its output, we have to do something like this:

```
OUTPUT=$(../../bin/phpstan analyze --no-progress --level 8 --error-format raw data/ || true)
echo "$OUTPUT"
../bashunit -a line_count 1 "$OUTPUT"
../bashunit -a contains 'Method TraitsCachingIssue\TestClassUsingTrait::doBar() should return stdClass but returns Exception.' "$OUTPUT"
```

The problem is that we're not really asserting that the commands returned exit code greater than zero, and also that we need to do the whole `OUTPUT=$(command || true)` dance.

Would be great if Bashunit provided a nicer way to do this :)

**Comment by Chemaclass** [comment]
@ondrejmirtes Can you give me an example of how would you vision the ideal use case? Especially, how would you use **bashunit** in this context (what would you like to have). This can help me going in the direction you need (test-first mindset), because right now I am not sure if I got the solution/problem right.
Also, if you can give me a link of a real example of this in your CI that might help too (to contextualize even more)

**Comment by Chemaclass** [comment]
I am playing around trying to feel the pain/problem
```php
<?php
class Testing {
  function bar(int $baz = 0) {
    return $baz;
  }
}
```
```bash
# Current example
OUTPUT=$("$PHPSTAN_PATH" analyze --no-progress --level 8 --error-format raw local/ || true)
echo "$OUTPUT"
./bashunit -a line_count 1 "$OUTPUT"
./bashunit -a contains 'Method teseting::bar() has no return type specified.' "$OUTPUT"

# Alternative(?)
OUTPUT=$("$PHPSTAN_PATH" analyze --no-progress --level 8 --error-format raw local/)
./bashunit -a line_count 1 "$OUTPUT"
./bashunit -a contains 'Method teseting::bar() has no return type specified.' "$OUTPUT"
```

Both example works just fine. This is why I mention I feel I need more context, because using the `Alternative()?` feels right to me, so most luckily I am missing something here :)

**Comment by staabm** [comment]
there is still no assertion for the exit code of the phpstan command

**Comment by Chemaclass** [comment]
@staabm you can assert the exit codes as well: https://bashunit.typeddevs.com/assertions#assert-exit-code

**Comment by staabm** [comment]
The github action will stol executing further commands as soon as a commands exits with non-zero. 

This means you can't assert after a command anymore as the execution already stopped
(Similar to a bash script executed with `set -x`)

**Comment by Chemaclass** [comment]
Have you tried `continue-on-error: true`. Eg:
```yaml
      - name: Run PHPUnit tests
        run: phpunit --testdox
        continue-on-error: true
```
Docs: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

Although, this might be similar as doing this ... 🤔 
```yaml
      - name: Run PHPUnit tests
        run: phpunit --testdox || true
```

**Comment by staabm** [comment]
so our use case is, that we want to assert the output and also the exit code of the phpstan command

we could assert the exit code with - I guess:
```
../bashunit -a assert_exit_code "1" "$(../../bin/phpstan analyze --no-progress --level 8 --error-format raw data/)"
```
but not the output.

or we can use
```
OUTPUT=$(../../bin/phpstan analyze --no-progress --level 8 --error-format raw data/ || true)
./bashunit -a line_count 1 "$OUTPUT"
```
to assert the output.. but we cannot check the exit code that way

**Comment by staabm** [comment]
I think something like this could work:

```
OUTPUT=$(../bashunit -a exit_code "1" "$(../../bin/phpstan analyze --no-progress --level 8 --error-format raw data/)")
```

in case we could instruct bashunit to pass the stdout of the command thru

**Comment by Chemaclass** [comment]
@ondrejmirtes @staabm how does this looks like for you? [Here you have the MVP](https://github.com/TypedDevs/bashunit/pull/336) based on your last comment, @staabm 

<img width="1507" alt="Screenshot 2024-09-24 at 22 24 58" src="https://github.com/user-attachments/assets/5e3ebbb3-a408-431c-bae3-63fc4f47f857">

I think this deferrable idea looks very sexy, however I am not sure about `callable:(...)` [instead of `$(...)`], maybe you have other suggestions? 🤔 

This POC is now only working on for the standalone `assert_exit_code` but I wonder if this use case might be beneficial in other assertions or other places. Maybe you can help me with this thought, what do you think about this so far? I will work tomorrow in adding tests 🧪

**Comment by staabm** [comment]
I would not mix the output of bashunit and the callable on the same output stream.

Bashunit output should go to stderr and the callable output to stdout.

The bashunit command should return exit code 0 if the assertion matched and otherwise non-zero

**Comment by Chemaclass** [comment]
@ondrejmirtes @staabm yes, that make sense. `bashunit` will render on stderr, and if you provide a eval script as last param then it will render its output on the stdout. Btw, I changed that `callable:(...)` thing to simply use `eval ...`

<img width="1447" alt="Screenshot 2024-09-25 at 19 22 02" src="https://github.com/user-attachments/assets/29f8c13b-5e2f-4013-9327-e1b7d5499065">

> By default stderr and stdout render to the terminal on the same way, but you can redirect the FD wherever you want.
